export type PortfolioSection = "data" | "business" | "product" | "learning" | "nebula"

export type PortfolioHighlight = {
  slug: string
  title: string
  section: PortfolioSection
  href: string
  date: string
  badge: string
  summary: string
  tags: string[]
}

export const portfolioHighlights: PortfolioHighlight[] = [
  {
    slug: "mercer-business-analyst",
    title: "Mercer - Business Analyst Internship",
    section: "business",
    href: "/business/mercer-business-analyst",
    date: "2025.12 - 2026.03",
    badge: "Top internship",
    summary: "Talent analytics, competency modeling, and people insights.",
    tags: ["People Analytics", "Competency Modeling", "HR"],
  },
  {
    slug: "abc-product-consultant",
    title: "A Better Community - AI Product Consultant",
    section: "business",
    href: "/business/abc-product-consultant",
    date: "2025.03 - 2025.08",
    badge: "Impact project",
    summary: "GenAI assistants and workflow design for nonprofit clients.",
    tags: ["AI Product", "User Research", "Deployment"],
  },
  {
    slug: "youtube-ai-content-strategy",
    title: "YouTube AI Content Strategy Optimization",
    section: "data",
    href: "/data/youtube-ai-content-strategy",
    date: "2025.10",
    badge: "Data flagship",
    summary: "Posting strategy, channel clustering, and view-lift modeling.",
    tags: ["Python", "SQL", "KMeans"],
  },
  {
    slug: "datathon-2025-supply-chain",
    title: "SUDATA x SUBAA Datathon 2025",
    section: "data",
    href: "/data/datathon-2025-supply-chain",
    date: "2025.10",
    badge: "First place",
    summary: "Supply-chain optimization using Gurobi and clustering.",
    tags: ["Optimisation", "Gurobi", "Time Series"],
  },
  {
    slug: "deloitte-digital-elite-2025",
    title: "Deloitte Digital Elite Challenge",
    section: "product",
    href: "/product/deloitte-digital-elite-2025",
    date: "2025.05",
    badge: "Runner-up",
    summary: "AI + audit product innovation and prototype delivery.",
    tags: ["AI + Audit", "Frontend", "Product"],
  },
  {
    slug: "gdgx-openai-hack",
    title: "GDG x OpenAI Hack Node Australia",
    section: "product",
    href: "/product/gdgx-openai-hack",
    date: "2025.08",
    badge: "Hackathon",
    summary: "Full-stack prototype built for the global AI hackathon.",
    tags: ["Vibe coding", "Full-stack", "GameFi"],
  },
  {
    slug: "kpmg-bluebird-it-audit",
    title: "KPMG Bluebird IT Audit Challenge",
    section: "business",
    href: "/business/kpmg-bluebird-it-audit",
    date: "2025.08",
    badge: "Finalist",
    summary: "IT audit, POS control points, and process risk logic.",
    tags: ["IT Audit", "Risk Analysis", "Process Mapping"],
  },
  {
    slug: "roland-berger-campus-2025",
    title: "Roland Berger Campus Challenge 2025",
    section: "business",
    href: "/business/roland-berger-campus-2025",
    date: "2025.06",
    badge: "Strategy lens",
    summary: "Humanoid robotics commercialization and entry-path analysis.",
    tags: ["Strategy", "Market Analysis", "Commercialization"],
  },
  {
    slug: "taylor-swift-engagement-analysis",
    title: "Taylor Swift Engagement Analysis",
    section: "data",
    href: "/data/taylor-swift-engagement-analysis",
    date: "2025.08",
    badge: "Deep dive",
    summary: "Sentiment evolution, persuasion pathways, and herding effects.",
    tags: ["Python", "YouTube API", "Sentiment"],
  },
  {
    slug: "food-delivery-insights",
    title: "Food Delivery Market Insights",
    section: "data",
    href: "/data/food-delivery-insights",
    date: "2025.08",
    badge: "In progress",
    summary: "Consumer segments, delivery drivers, and promo impact.",
    tags: ["Python", "Clustering", "Causal Inference"],
  },
  {
    slug: "greater-sydney-sa2-scoring",
    title: "Greater Sydney SA2 Resources Scoring",
    section: "data",
    href: "/data/greater-sydney-sa2-scoring",
    date: "2025.01",
    badge: "Geo analytics",
    summary: "Composite scoring for accessibility and resources.",
    tags: ["PostgreSQL", "Index Scoring", "Machine Learning"],
  },
  {
    slug: "abc-ai-development",
    title: "A Better Community - AI Development",
    section: "product",
    href: "/product/abc-ai-development",
    date: "2025.3 - Present",
    badge: "Internship",
    summary: "GenAI products for community-facing use cases.",
    tags: ["Research Design", "Prompt Engineering", "API"],
  },
  {
    slug: "kpmg-innovate-day-2025",
    title: "KPMG Innovate Day 2025",
    section: "product",
    href: "/product/kpmg-innovate-day-2025",
    date: "2024.10",
    badge: "Product lab",
    summary: "Digital products & insights for innovation programs.",
    tags: ["Product", "AI+Audit", "Business Plan"],
  },
  {
    slug: "aussie-adventure",
    title: "Comm-Stem x Canva Hackathon 2025",
    section: "product",
    href: "/product/aussie-adventure",
    date: "2025.09",
    badge: "Creative build",
    summary: "Travel, palette, and weather-driven product prototype.",
    tags: ["Frontend", "API Integration", "Recommender"],
  },
]
