export type OrbitSection = "business" | "data" | "product"

export type OrbitItem = {
  slug: string
  title: string
  section: OrbitSection
  href: string
  industries: string[]
}

// Auto-synced (generated once) from:
// - app/business/page.tsx
// - app/data/page.tsx
// - app/product/page.tsx
// Keep this list "scan-friendly": project name + industries only.
export const orbitItems: OrbitItem[] = [
  {
    slug: "mercer-business-analyst",
    title: "Business Analyst",
    section: "business",
    href: "/business/mercer-business-analyst",
    industries: ["HR Consulting", "People Analytics", "Enterprise"],
  },
  {
    slug: "abc-product-consultant",
    title: "AI Product Consultant",
    section: "business",
    href: "/business/abc-product-consultant",
    industries: ["Nonprofit", "Education", "Senior Care", "AI Applications"],
  },
  {
    slug: "kpmg-bluebird-it-audit",
    title: "POS / Payments IT Audit Case",
    section: "business",
    href: "/business/kpmg-bluebird-it-audit",
    industries: ["Retail Tech", "Payments", "IT Audit"],
  },
  {
    slug: "net-zero-challenge-gys",
    title: "Smart Green Homestay",
    section: "business",
    href: "/business/net-zero-challenge-gys",
    industries: ["Sustainability", "Climate", "Tourism"],
  },
  {
    slug: "mersen-campus-brand-activation",
    title: "Invisible Guardian",
    section: "business",
    href: "/business/mersen-campus-brand-activation",
    industries: ["Industrial Brand", "B2B", "Marketing"],
  },
  {
    slug: "YuanQi-forest-universe-2026",
    title: "Code Energy Water",
    section: "business",
    href: "/business/YuanQi-forest-universe-2026",
    industries: ["Beverage", "Consumer Goods", "Brand Innovation"],
  },
  {
    slug: "roland-berger-campus-2025",
    title: "Humanoid Robot GTM",
    section: "business",
    href: "/business/roland-berger-campus-2025",
    industries: ["Humanoid Robotics", "Advanced Manufacturing", "AI Hardware"],
  },
  {
    slug: "mengniu-campus-innovation-2025",
    title: "Clear-Mind Challenge Bottle",
    section: "business",
    href: "/business/mengniu-campus-innovation-2025",
    industries: ["FMCG", "Dairy", "Consumer Goods"],
  },
  {
    slug: "loreal-brandstorm",
    title: "Men’s Beauty Tech Concept",
    section: "business",
    href: "/business/loreal-brandstorm",
    industries: ["Beauty", "Consumer Goods", "Men's Skincare"],
  },
  {
    slug: "saiep-management",
    title: "Management Consultant",
    section: "business",
    href: "/business/saiep-management",
    industries: ["Nonprofit", "Sports", "Community"],
  },
  {
    slug: "ey-esg-innovation-2025",
    title: "AI × ESG Luxury Supply Chain",
    section: "business",
    href: "/business/ey-esg-innovation-2025",
    industries: ["Luxury", "Supply Chain", "ESG"],
  },
  {
    slug: "kpmg-esg-case-competition",
    title: "Automotive Supply Chain ESG",
    section: "business",
    href: "/business/kpmg-esg-case-competition",
    industries: ["Automotive", "Supply Chain", "ESG"],
  },
  {
    slug: "allegro-fund-pe-competition-2024",
    title: "Bega Group ESG & Valuation",
    section: "business",
    href: "/business/allegro-fund-pe-competition-2024",
    industries: ["Dairy", "Consumer Staples", "ESG"],
  },
  {
    slug: "deloitte-technology",
    title: "Digital Consulting Simulation",
    section: "business",
    href: "/business/deloitte-technology",
    industries: ["Consulting", "Technology", "Transformation"],
  },
  {
    slug: "accenture-strategy-consulting",
    title: "Strategy Consulting Simulation",
    section: "business",
    href: "/business/accenture-strategy-consulting",
    industries: ["Consulting", "Strategy", "Business Services"],
  },
  {
    slug: "aerotropolis-south-connector-2026",
    title: "Aerotropolis South Connector",
    section: "business",
    href: "/business/aerotropolis-south-connector-2026",
    industries: ["Infrastructure", "Transport", "Public Sector"],
  },
  {
    slug: "commonwealth-treasury-case",
    title: "Policy Package Evaluation",
    section: "business",
    href: "/business/commonwealth-treasury-case",
    industries: ["Banking", "Public Policy", "Macroeconomics"],
  },

  {
    slug: "datathon-2025-supply-chain",
    title: "Supply Chain Optimization (24h)",
    section: "data",
    href: "/data/datathon-2025-supply-chain",
    industries: ["Supply Chain", "Operations", "E-commerce"],
  },
  {
    slug: "meituan-subsidy-efficiency",
    title: "Subsidy Incrementality (PSM)",
    section: "data",
    href: "/data/meituan-subsidy-efficiency",
    industries: ["E-commerce", "Local Services", "Finance"],
  },
  {
    slug: "pathology-image-classification",
    title: "H&E Tumour vs Immune Cells",
    section: "data",
    href: "/data/pathology-image-classification",
    industries: ["Healthcare", "Medical Imaging", "Machine Learning"],
  },
  {
    slug: "future-financial-analyst",
    title: "Growth-Based Repricing Framework",
    section: "data",
    href: "/data/future-financial-analyst",
    industries: ["Finance", "Asset Management", "Public Policy"],
  },
  {
    slug: "youtube-ai-content-strategy",
    title: "Posting Window Lift Model",
    section: "data",
    href: "/data/youtube-ai-content-strategy",
    industries: ["Entertainment", "Creator Economy", "Marketing"],
  },
  {
    slug: "short-drama-text-analysis",
    title: "Human–AI Dialogue Mining",
    section: "data",
    href: "/data/short-drama-text-analysis",
    industries: ["Beauty", "Consumer Services", "AI Training"],
  },
  {
    slug: "ai-wave-nvda-forecast",
    title: "NVDA Cycle Forecast",
    section: "data",
    href: "/data/ai-wave-nvda-forecast",
    industries: ["Finance", "Semiconductors"],
  },
  {
    slug: "education-experience-earnings-model",
    title: "Education vs Experience on Earnings",
    section: "data",
    href: "/data/education-experience-earnings-model",
    industries: ["Labor Economics", "Education", "Public Policy"],
  },
  {
    slug: "wine-quality-analysis",
    title: "Wine Quality Drivers",
    section: "data",
    href: "/data/wine-quality-analysis",
    industries: ["Food & Beverage", "Agri-food"],
  },
  {
    slug: "disaster-risk-insurance",
    title: "Disaster Risk & Insurance Levers",
    section: "data",
    href: "/data/disaster-risk-insurance",
    industries: ["Insurance", "Public Policy", "Climate Risk"],
  },
  {
    slug: "data1x01-study",
    title: "DATA1X01 Learning Survey",
    section: "data",
    href: "/data/data1x01-study",
    industries: ["Education", "Higher Ed"],
  },
  {
    slug: "employer-income-correlation-au",
    title: "Employer Types vs Income (AU)",
    section: "data",
    href: "/data/employer-income-correlation-au",
    industries: ["Labor Economics", "Public Policy"],
  },
  {
    slug: "greater-sydney-sa2-scoring",
    title: "Sydney SA2 Resource Index",
    section: "data",
    href: "/data/greater-sydney-sa2-scoring",
    industries: ["Urban Analytics", "Public Policy"],
  },
  {
    slug: "pima-diabetes",
    title: "Classifier Benchmark (Pima vs Occupancy)",
    section: "data",
    href: "/data/pima-diabetes",
    industries: ["Healthcare", "Machine Learning"],
  },
  {
    slug: "taylor-swift-engagement-analysis",
    title: "Engagement & Herding Signals",
    section: "data",
    href: "/data/taylor-swift-engagement-analysis",
    industries: ["Entertainment", "Social Media", "Marketing"],
  },
  {
    slug: "revenue-prediction",
    title: "QSR Daily Outlet Revenue",
    section: "data",
    href: "/data/revenue-prediction",
    industries: ["Retail", "Hospitality", "Finance"],
  },
  {
    slug: "apmcm-2024",
    title: "APMCM Modeling Solution",
    section: "data",
    href: "/data/apmcm-2024",
    industries: ["Research", "Applied Math"],
  },
  {
    slug: "mcm-icm-2025",
    title: "MCM/ICM Modeling Solution",
    section: "data",
    href: "/data/mcm-icm-2025",
    industries: ["Research", "Applied Math"],
  },

  {
    slug: "abc-ai-development",
    title: "AI Development",
    section: "product",
    href: "/product/abc-ai-development",
    industries: ["Nonprofit", "AI Applications"],
  },
  {
    slug: "agentlens",
    title: "AgentLens",
    section: "product",
    href: "/product/agentlens",
    industries: ["AI", "Developer Tools", "Software"],
  },
  {
    slug: "foodguard-lyra-buildthon",
    title: "FoodGuard",
    section: "product",
    href: "/product/foodguard-lyra-buildthon",
    industries: ["HealthTech", "Consumer App"],
  },
  {
    slug: "deloitte-digital-elite-2025",
    title: "AI + Audit Product Concept",
    section: "product",
    href: "/product/deloitte-digital-elite-2025",
    industries: ["Professional Services", "Audit", "Enterprise"],
  },
  {
    slug: "gdgx-openai-hack",
    title: "YOLO·AU",
    section: "product",
    href: "/product/gdgx-openai-hack",
    industries: ["Social", "Community", "Creator Economy"],
  },
  {
    slug: "ccf-tech-for-good-2025",
    title: "Tech-for-Good Prototype",
    section: "product",
    href: "/product/ccf-tech-for-good-2025",
    industries: ["Social Impact", "Media", "Accessibility"],
  },
  {
    slug: "adventurex-2025",
    title: "YOLO Growth Stock",
    section: "product",
    href: "/product/adventurex-2025",
    industries: ["Community", "Career", "EdTech"],
  },
  {
    slug: "kpmg-innovate-day-2025",
    title: "Innovation Day Sprint",
    section: "product",
    href: "/product/kpmg-innovate-day-2025",
    industries: ["Professional Services", "Audit", "Enterprise"],
  },
  {
    slug: "microsoft-chat-hack-promptathon",
    title: "Promptathon Prototype",
    section: "product",
    href: "/product/microsoft-chat-hack-promptathon",
    industries: ["AI", "Enterprise Software"],
  },
  {
    slug: "ai-esg-circular-fashion",
    title: "Circular Fashion ESG Scoring",
    section: "product",
    href: "/product/ai-esg-circular-fashion",
    industries: ["Fashion", "ESG", "Sustainability"],
  },
  {
    slug: "aussie-adventure",
    title: "Aussie Adventure",
    section: "product",
    href: "/product/aussie-adventure",
    industries: ["Travel", "Consumer App"],
  },
  {
    slug: "xuetu-hackathon",
    title: "XueTu Marketplace",
    section: "product",
    href: "/product/xuetu-hackathon",
    industries: ["Education", "Local Services"],
  },
  {
    slug: "xuetu-amap",
    title: "XueTu × Amap",
    section: "product",
    href: "/product/xuetu-amap",
    industries: ["Education", "Location Services"],
  },
]

